name: test-terraform-deploy

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/azure-login@v2
        with: 
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
