name: test-terraform-deploy

on:
  push:

permissions:
  id-token: write

defaults:
  run:
    shell: bash
    working-directory: ./terraform

jobs:
  job1:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with: 
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: hashicorp/setup-terraform@v1
      - run: terraform init
      - run: terraform plan
